output_directory: "/home/glbrc.org/millican/repos/trait-charmer/workflow/references/sourmash_taxonomy"
working_directory: "/home/glbrc.org/millican/repos/trait-charmer/workflow"
taxa: ["bacteria", "archaea", "fungi", "viral", "plant", "invertebrate", "protozoa"]
database: ["refseq", "genbank"]
ncbi_taxonomy: "/home/glbrc.org/millican/ref_db/ncbi_taxdmp"